Args = --add-modules=java.desktop \
  -Djava.awt.headless=true \
  -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Jdk14Logger \
  -H:+AddAllCharsets \
  --initialize-at-run-time=\
    org.apache.pdfbox,\
    org.apache.fontbox,\
    sun.java2d.Disposer
