Args = --add-modules=java.desktop \
  -Djava.awt.headless=true \
  --initialize-at-run-time=\
    org.apache.pdfbox,\
    org.apache.fontbox,\
    com.sun.imageio,\
    java.awt,\
    javax.imageio,\
    sun.awt,\
    sun.font,\
    sun.java2d
